// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njsssqagvfzjiyctbaae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qc3NzcWFndmZ6aml5Y3RiYWFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MTkyNDQsImV4cCI6MjA2MTA5NTI0NH0.cXwd4hWMV_optu4QeY-bEhhmJR8TrMbbNsHl12w62vs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);